### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by garymooney** [quoxel/VariableGridLayoutGroup#1]
Hi quoxel,

Looks like a great UI addon, thanks! Although I'm getting some compiler errors. Not sure if the Unity version matters too much but I'm using 5.5.0f3. 

1. Line 93: missing semicolon.
2. Line 104: missing arguments for LayoutUtility.GetPreferredWidth and LayoutUtility.GetPreferredHeight. I haven't gone through the code in detail but I'm assuming the argument is meant to be rectTransform?
3. Line 142: Variable not declared, missing variable type, assuming float[].
4. Line 194: Cannot recognize type VGridCell, not too sure what to do about this one.
5.Line 330: Variable not declared, missing variable type, assuming float[].

**Comment by mistertricks** [comment]
Thanks for the notes! As you can tell from the delay in replying, I don't look at Github very often - and I didn't get an email notification. I had left corrected code in an unmerged branch by mistake. I've merged it into the master branch now and checked it, and it should now work. It also has some extra functionality.
